// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnffte4KNvypJ3JAp5o7PjucHLMVhjh-k',
    appId: '1:5860130041:web:7372ac4f1f60587280f628',
    messagingSenderId: '5860130041',
    projectId: 'caqmmoon',
    authDomain: 'caqmmoon.firebaseapp.com',
    storageBucket: 'caqmmoon.firebasestorage.app',
    measurementId: 'G-9RN5M0TQFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTbWdGfKC3gqQ8vf77ArXbj7_x5W1A2fo',
    appId: '1:5860130041:android:4373d5df6d33170f80f628',
    messagingSenderId: '5860130041',
    projectId: 'caqmmoon',
    storageBucket: 'caqmmoon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2GKd1-N-sy8TvRfRzkXg3TJQABpelbP8',
    appId: '1:5860130041:ios:2e722444dc462e4780f628',
    messagingSenderId: '5860130041',
    projectId: 'caqmmoon',
    storageBucket: 'caqmmoon.firebasestorage.app',
    iosBundleId: 'com.example.caqmmoon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2GKd1-N-sy8TvRfRzkXg3TJQABpelbP8',
    appId: '1:5860130041:ios:2e722444dc462e4780f628',
    messagingSenderId: '5860130041',
    projectId: 'caqmmoon',
    storageBucket: 'caqmmoon.firebasestorage.app',
    iosBundleId: 'com.example.caqmmoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnffte4KNvypJ3JAp5o7PjucHLMVhjh-k',
    appId: '1:5860130041:web:fdd283fd70e6cbc580f628',
    messagingSenderId: '5860130041',
    projectId: 'caqmmoon',
    authDomain: 'caqmmoon.firebaseapp.com',
    storageBucket: 'caqmmoon.firebasestorage.app',
    measurementId: 'G-LCDKZWDEXX',
  );
}
